### PR TITLE
ES6 문법 + user 변수 owner로 변경(재선언 방지)

### PR DESCRIPTION
**Pull request by dn1t**

### CODE REVIEW

**Comment by muno9748** [comment]
# 와!! 쌘즈
### 샌즈가 곧 와고 와가 곧 샌즈입니다
 - 네 그렇다고요

**Comment by muno9748** [comment]
̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢ ̧̼͔̬̮̣̪̬̥̫̬͎͚͔ͨͨͣ̈́͛̒ͦ͛̚͜͢

**Comment by thoratica** [comment]
빨리 좀......

**Comment by chamwhy** [comment]
ㄴㅇㄱ

**Comment by muno9748** [comment]
ㄴㅇㄱㄴㅇㄱ

**Pull request closed without merging**
